### ISSUE TITLE
do this work?

### ISSUE THREAD

**Issue by MikkelDK** [Yariya/100upAttackEmbed#1]
@Yariya 

Do this work still?

```
./index.js:121
                    .setAuthor(OVH Alerts', 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Flag_of_Canada_%28Pantone%29.svg/1200px-Flag_of_Canada_%28Pantone%29.svg.png', 'https://yariya.dev/')
                               ^^^

SyntaxError: missing ) after argument list
```
Seems error. =D

**Comment by Yariya** [comment]
my bad

.setAuthor('OVH Alerts', 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Flag_of_Canada_%28Pantone%29.svg/1200px-Flag_of_Canada_%28Pantone%29.svg.png', 'siteurl')

this should work

**Comment by MikkelDK** [comment]
@Yariya 

How to get this work seems it don't tell me howto =D

```
marc@vm-m4rc-01:~$ node index.js
(node:1981423) UnhandledPromiseRejectionWarning: Error [TOKEN_INVALID]: An invalid token was provided.
    at WebSocketManager.connect (/home/marc/node_modules/discord.js/src/client/websocket/WebSocketManager.js:133:26)
    at Client.login (/home/marc/node_modules/discord.js/src/client/Client.js:223:21)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:1981423) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:1981423) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by Yariya** [comment]
Your token is invalid

**Comment by ItMeVaxi** [comment]
@MikkelDK  your Token is invalid KekW

**Comment by MikkelDK** [comment]
Oh. README.md doesn't explain where to "place" token =) 

About its the: [Line 60](https://github.com/Yariya/100upAttackEmbed/blob/main/index.js#L60)

**Comment by Yariya** [comment]
I will fork this soon (Reworking)

**Comment by string-null** [comment]
bro, when i make $mbps or mbps the bots goes offline

**Comment by Yariya** [comment]
It will be reworked (1-7 days) so wait and keep checking my GitHub

**Comment by MikkelDK** [comment]
@Yariya Any update? 1-7 days have been passed. :D

**Comment by Yariya** [comment]
I will work on it today!

**Comment by MikkelDK** [comment]
> I will work on it today!

@Yariya Still working on an update or? ;/ zzzz =D
